In [1]:
import torch
import pandas as pd
import fitz
from tqdm.auto import tqdm
from spacy.lang.en import English

In [2]:
pdf_path = "D:\\Projects\\Local_Mini_RAG\\data\\human-nutrition-text.pdf"

def text_formatter(text: str) -> str:
    cleaned_text = text.replace("\n", " ").strip()
    return cleaned_text

def open_and_read_pdf(pdf_path: str) -> list[dict]:
    doc = fitz.open(pdf_path)
    pages_and_texts = []
    for page_number, page in tqdm(enumerate(doc)):  # iterate the document pages
        text = page.get_text()  # get plain text encoded as UTF-8
        text = text_formatter(text)
        pages_and_texts.append({"page_number": page_number - 41,  # adjust page numbers since our PDF starts on page 42
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count_raw": len(text.split(". ")),
                                "page_token_count": len(text) / 4,  # 1 token = 4 chars
                                "text": text})
    return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts[200]

0it [00:00, ?it/s]

{'page_number': 159,
 'page_char_count': 1762,
 'page_word_count': 303,
 'page_sentence_count_raw': 15,
 'page_token_count': 440.5,
 'text': 'thermoregulation is to balance heat gain with heat loss and body  water plays an important role in accomplishing this. Human life  is supported within a narrow range of temperature, with the  temperature set point of the body being 98.6°F (37°C). Too low or  too high of a temperature causes enzymes to stop functioning and  metabolism is halted. At 82.4°F (28°C) muscle failure occurs and  hypothermia sets in. At the opposite extreme of 111.2°F (44°C) the  central nervous system fails and death results. Water is good at  storing heat, an attribute referred to as heat capacity and thus helps  maintain the temperature set point of the body despite changes in  the surrounding environment.  There are several mechanisms in place that move body water  from place to place as a method to distribute heat in the body and  equalize body temperature (Figure 3.4 “Thermoregulatory Center”).  The hypothalamus in the brain is the thermoregulatory center. The  hypothalamus contains special protein sensors that detect blood  temperature. The skin also contains temperature sensors that  respond quickly to changes in immediate surroundings. In response  to cold sensors in the skin, a neural signal is sent to the  hypothalamus, which then sends a signal to smooth muscle tissue  surrounding blood vessels causing them to constrict and reduce  blood flow. This reduces heat lost to the environment. The  hypothalamus also sends signals to muscles to erect hairs and shiver  and to endocrine glands like the thyroid to secrete hormones  capable of ramping up metabolism. These actions increase heat  conservation and stimulate its production in the body in response  to cooling temperatures.  Figure 3.4 Thermoregulatory Center  Water’s Importance to Vitality  |  159'}

In [40]:
nlp = English()

nlp.add_pipe("sentencizer")

doc = nlp("This is a sentence. This is another sentence. And this is yet another sentence.")

assert len(list(doc.sents)) == 3

list(doc.sents)

[This is a sentence.,
 This is another sentence.,
 And this is yet another sentence.]

In [41]:
for item in tqdm(pages_and_texts):
    # split the text into sentences using spacy
    item["sentences"] = list(nlp(item["text"]).sents)
    # convert the sentences to strings
    item["sentences"] = [str(sentence) for sentence in item["sentences"]]
    # count the number of sentences in the page
    item["page_sentence_count_spacy"] = len(item["sentences"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [42]:
import random
random.sample(pages_and_texts, 1)

[{'page_number': 969,
  'page_char_count': 1329,
  'page_word_count': 211,
  'page_sentence_count_raw': 13,
  'page_token_count': 332.25,
  'text': 'progresses, the amount of red blood cells will increase to catch up  with the total blood volume.  Vitamin D and Calcium  Vitamin D regulates the calcium and phosphorus absorption and  metabolism and plays a key role in maintaining optimal bone health.  There is also growing evidence that vitamin D is important for  other aspect of athletic performance such as injury prevention,  rehabilitation, and muscle metabolism. Individuals who primarily  practice indoors are at a larger risk for a vitamin D deficiency and  should ensure they are consuming foods high in vitamin D to  maintain sufficient vitamin D status.9  Calcium is especially important for the growth, maintenance, and  repair of bone tissue. Low calcium intake occurs in athletes with  RED-S, menstrual dysfunction, and those who avoid dairy products.  A diet inadequate in calcium increases the risk for low bone mineral  density \xa0which ultimately leads to stress fractures.  Antioxidant nutrients  Antioxidant nutrients play an important role in protecting cell  9.\xa0Nutrition and Athletic Performance. (2016). American  College of Sports Medicine. Medicine & Science in Sports  & Exercise, 48(3), 543- 568. \xa0https://journals.lww.com/ acsm-msse/Fulltext/2016/03000/ Nutrition_and_Athletic_Performance.25.aspx. Accessed  March 17, 2018.  Sports Nutrition  |  969',
  'sentences': ['progresses, the amount of red blood cells will increase to catch up  with the total blood volume.',
   ' Vitamin D and Calcium  Vitamin D regulates the calcium and phosphorus absorption and  metabolism and plays a key role in maintaining optimal bone health.',
   ' There is also growing evidence that vitamin D is important for  other aspect of athletic performance such as injury prevention,  rehabilitation, and muscle metabolism.',
   'Individuals who primarily  practice indoors are at a larger risk for a vitamin D deficiency and  should ensure they are consuming foods high in vitamin D to  maintain sufficient vitamin D status.9  Calcium is especially important for the growth, maintenance, and  repair of bone tissue.',
   'Low calcium intake occurs in athletes with  RED-S, menstrual dysfunction, and those who avoid dairy products.',
   ' A diet inadequate in calcium increases the risk for low bone mineral  density \xa0which ultimately leads to stress fractures.',
   ' Antioxidant nutrients  Antioxidant nutrients play an important role in protecting cell  9.',
   '\xa0Nutrition and Athletic Performance. (',
   '2016).',
   'American  College of Sports Medicine.',
   'Medicine & Science in Sports  & Exercise, 48(3), 543- 568.',
   '\xa0https://journals.lww.com/ acsm-msse/Fulltext/2016/03000/ Nutrition_and_Athletic_Performance.25.aspx.',
   'Accessed  March 17, 2018.',
   ' Sports Nutrition  |  969'],
  'page_sentence_count_spacy': 14}]

In [43]:
df = pd.DataFrame(pages_and_texts)

In [44]:
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,198.30,9.97,287.00,10.32
std,348.86,560.38,95.76,6.19,140.10,6.30
min,-41.00,0.00,1.00,1.00,0.00,0.00
25%,260.75,762.00,134.00,4.00,190.50,5.00
50%,562.50,1231.50,214.50,10.00,307.88,10.00
75%,864.25,1603.50,271.00,14.00,400.88,15.00
max,1166.00,2308.00,429.00,32.00,577.00,28.00

In [45]:
num_sentence_chunk_size = 10

def split_list(input_list: list[str],
                slice_size: int= num_sentence_chunk_size) -> list[list[str]]:
    
    return[input_list[i:i + slice_size] for i in range(0, len(input_list), slice_size)]

test_list = list(range(25))
split_list(test_list)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [46]:
for item in tqdm(pages_and_texts):
    # split the sentences into chunks of num_sentence_chunk_size
    item["sentence_chunks"] = split_list(input_list=item["sentences"], slice_size=num_sentence_chunk_size)
    item["sentence_chunk_count"] = len(item["sentence_chunks"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [47]:
random.sample(pages_and_texts, 1)

[{'page_number': 311,
  'page_char_count': 787,
  'page_word_count': 145,
  'page_sentence_count_raw': 5,
  'page_token_count': 196.75,
  'text': 'Image by  Openstax  Biology / CC  BY 4.0  Interestingly, some naturally occurring trans fats do not pose the  same health risks as their artificially engineered counterparts.  These trans fats are found in ruminant animals such as cows, sheep,  and goats, resulting in trans fatty acids being present in our meat,  milk, and other dairy product supply. Reports from the US  Department of Agriculture (USDA) indicate that these trans fats  comprise 15 to 20 percent of the total trans-fat intake in our diet.  While we know that trans fats are not exactly harmless, it seems  that any negative effect naturally occurring trans fats have are  counteracted by the presence of other fatty acid molecules in these  animal products, which work to promote human health.  How Lipids Work  |  311',
  'sentences': ['Image by  Openstax  Biology / CC  BY 4.0  Interestingly, some naturally occurring trans fats do not pose the  same health risks as their artificially engineered counterparts.',
   ' These trans fats are found in ruminant animals such as cows, sheep,  and goats, resulting in trans fatty acids being present in our meat,  milk, and other dairy product supply.',
   'Reports from the US  Department of Agriculture (USDA) indicate that these trans fats  comprise 15 to 20 percent of the total trans-fat intake in our diet.',
   ' While we know that trans fats are not exactly harmless, it seems  that any negative effect naturally occurring trans fats have are  counteracted by the presence of other fatty acid molecules in these  animal products, which work to promote human health.',
   ' How Lipids Work  |  311'],
  'page_sentence_count_spacy': 5,
  'sentence_chunks': [['Image by  Openstax  Biology / CC  BY 4.0  Interestingly, some naturally occurring trans fats do not pose the  same health risks as their artificially engineered counterparts.',
    ' These trans fats are found in ruminant animals such as cows, sheep,  and goats, resulting in trans fatty acids being present in our meat,  milk, and other dairy product supply.',
    'Reports from the US  Department of Agriculture (USDA) indicate that these trans fats  comprise 15 to 20 percent of the total trans-fat intake in our diet.',
    ' While we know that trans fats are not exactly harmless, it seems  that any negative effect naturally occurring trans fats have are  counteracted by the presence of other fatty acid molecules in these  animal products, which work to promote human health.',
    ' How Lipids Work  |  311']],
  'sentence_chunk_count': 1}]

In [48]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy,sentence_chunk_count
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,198.30,9.97,287.00,10.32,1.53
std,348.86,560.38,95.76,6.19,140.10,6.30,0.64
min,-41.00,0.00,1.00,1.00,0.00,0.00,0.00
25%,260.75,762.00,134.00,4.00,190.50,5.00,1.00
50%,562.50,1231.50,214.50,10.00,307.88,10.00,1.00
75%,864.25,1603.50,271.00,14.00,400.88,15.00,2.00
max,1166.00,2308.00,429.00,32.00,577.00,28.00,3.00

In [49]:
import re

pages_and_chunks = []

for item in tqdm(pages_and_texts):
    for sentence_chunk in item["sentence_chunks"]:
        chunk_dict = {}
        chunk_dict["page_number"] = item["page_number"]

        # join the sentences in the chunk back into a single string
        joined_sentence_chunk = " ".join(sentence_chunk).replace("  ", " ").strip()
        # add space after period if there isn't one already
        joined_sentence_chunk = re.sub(r"\.([A-Z])", r". \1", joined_sentence_chunk)
        # add the joined sentence chunk to the chunk dict
        chunk_dict["sentence_chunk"] = joined_sentence_chunk

        chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
        chunk_dict["chunk_word_count"] = len(joined_sentence_chunk.split(" "))
        chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4
        pages_and_chunks.append(chunk_dict)

len(pages_and_chunks)

  0%|          | 0/1208 [00:00<?, ?it/s]

1843

In [50]:
random.sample(pages_and_chunks, 1)

[{'page_number': 926,
  'sentence_chunk': 'Vision Problems Many older people suffer from vision problems and a loss of vision. Age-related macular degeneration is the leading cause of blindness in Americans over age sixty.6 This disorder can make food planning and preparation extremely difficult and people who suffer from it often must depend on caregivers for their meals. Self-feeding also may be difficult if an elderly person cannot see his or her food clearly. Friends and family members can help older adults with shopping and cooking. Food-assistance programs for older adults (such as Meals on Wheels) can also be helpful. Diet may help to prevent macular degeneration. Consuming colorful fruits and vegetables increases the intake of lutein and zeaxanthin. Several studies have shown that these antioxidants provide protection for the eyes. Lutein and zeaxanthin are found in green, leafy vegetables such as spinach, kale, and collard greens, and also corn, peaches, squash, broccoli, Brussels sprouts, orange juice, and honeydew melon.7 Longevity and Nutrition The foods you consume in your younger years influence your health as you age. Good nutrition and regular physical activity can help you 6.',
  'chunk_char_count': 1168,
  'chunk_word_count': 181,
  'chunk_token_count': 292.0}]

In [51]:
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count      1843.00           1843.00           1843.00            1843.00
mean        583.38            735.14            113.03             183.78
std         347.79            447.64             71.27             111.91
min         -41.00             12.00              3.00               3.00
25%         280.50            315.00             45.00              78.75
50%         586.00            747.00            114.00             186.75
75%         890.00           1119.00            174.00             279.75
max        1166.00           1832.00            298.00             458.00

In [52]:
min_token_length = 30

pages_and_chunks_over_min_token_length = df[df["chunk_token_count"]> min_token_length].to_dict(orient="records")
random.sample(pages_and_chunks_over_min_token_length,k=1)

[{'page_number': 793,
  'sentence_chunk': 'Fats should make up 25 to 35 percent of daily calories, and those calories should come from healthy fats, such as avocados and salmon. It is not recommended for pregnant women to be on a very low-fat diet, since it would be hard to meet the needs of essential fatty acids and fat-soluble vitamins. Fatty acids are important during pregnancy because they support the baby’s brain and eye development. Fluids Fluid intake must also be monitored. According to the IOM, pregnant women should drink 2.3 liters (about 10 cups) of liquids per day to provide enough fluid for blood production. It is also important to drink liquids during and after physical activity or when it is hot and humid outside, to replace fluids lost to perspiration. Pregnancy | 793',
  'chunk_char_count': 751,
  'chunk_word_count': 129,
  'chunk_token_count': 187.75}]

In [54]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(model_name_or_path="all-mpnet-base-v2", device="cuda" if torch.cuda.is_available() else "cpu")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [55]:
%%time

for item in tqdm(pages_and_chunks_over_min_token_length):
    item["embedding"] = embedding_model.encode(item["sentence_chunk"])

  0%|          | 0/1680 [00:00<?, ?it/s]

CPU times: total: 7min 10s
Wall time: 56.2 s

In [56]:
%%time

text_chunk = [item['sentence_chunk'] for item in pages_and_chunks_over_min_token_length]
text_chunk[419]

CPU times: total: 0 ns
Wall time: 587 μs

'often. • Calm your “sweet tooth” by eating fruits, such as berries or an apple. • Replace sugary soft drinks with seltzer water, tea, or a small amount of 100 percent fruit juice added to water or soda water. The Food Industry: Functional Attributes of Carbohydrates and the Use of Sugar Substitutes In the food industry, both fast-releasing and slow-releasing carbohydrates are utilized to give foods a wide spectrum of functional attributes, including increased sweetness, viscosity, bulk, coating ability, solubility, consistency, texture, body, and browning capacity. The differences in chemical structure between the different carbohydrates confer their varied functional uses in foods. Starches, gums, and pectins are used as thickening agents in making jam, cakes, cookies, noodles, canned products, imitation cheeses, and a variety of other foods. Molecular gastronomists use slow- releasing carbohydrates, such as alginate, to give shape and texture to their fascinating food creations. Adding fiber to foods increases bulk. Simple sugars are used not only for adding sweetness, but also to add texture, consistency, and browning. In ice cream, the combination of sucrose and corn syrup imparts sweetness as well as a glossy appearance and smooth texture.'

In [57]:
%%time
text_chunk_embedding = embedding_model.encode(text_chunk, batch_size=16, convert_to_tensor=True)

text_chunk_embedding

CPU times: total: 2min 37s
Wall time: 32.3 s

tensor([[ 0.0674,  0.0902, -0.0051,  ..., -0.0221, -0.0232,  0.0126],
        [ 0.0552,  0.0592, -0.0166,  ..., -0.0120, -0.0103,  0.0227],
        [ 0.0280,  0.0340, -0.0206,  ..., -0.0054,  0.0213,  0.0313],
        ...,
        [ 0.0771,  0.0098, -0.0122,  ..., -0.0409, -0.0752, -0.0241],
        [ 0.1030, -0.0165,  0.0083,  ..., -0.0574, -0.0283, -0.0295],
        [ 0.0864, -0.0125, -0.0113,  ..., -0.0522, -0.0337, -0.0299]],
       device='cuda:0')

In [58]:
pages_and_chunks_over_min_token_length[419]

{'page_number': 277,
 'sentence_chunk': 'often. • Calm your “sweet tooth” by eating fruits, such as berries or an apple. • Replace sugary soft drinks with seltzer water, tea, or a small amount of 100 percent fruit juice added to water or soda water. The Food Industry: Functional Attributes of Carbohydrates and the Use of Sugar Substitutes In the food industry, both fast-releasing and slow-releasing carbohydrates are utilized to give foods a wide spectrum of functional attributes, including increased sweetness, viscosity, bulk, coating ability, solubility, consistency, texture, body, and browning capacity. The differences in chemical structure between the different carbohydrates confer their varied functional uses in foods. Starches, gums, and pectins are used as thickening agents in making jam, cakes, cookies, noodles, canned products, imitation cheeses, and a variety of other foods. Molecular gastronomists use slow- releasing carbohydrates, such as alginate, to give shape and texture to their fascinating food creations. Adding fiber to foods increases bulk. Simple sugars are used not only for adding sweetness, but also to add texture, consistency, and browning. In ice cream, the combination of sucrose and corn syrup imparts sweetness as well as a glossy appearance and smooth texture.',
 'chunk_char_count': 1264,
 'chunk_word_count': 190,
 'chunk_token_count': 316.0,
 'embedding': array([ 3.36195640e-02, -6.33050455e-03,  1.35672651e-02, -1.72720582e-03,
         7.37232342e-03, -1.12093268e-02, -7.77235404e-02, -1.98784424e-03,
         4.41749096e-02,  1.84354987e-02,  1.08429941e-03, -4.48691733e-02,
        -1.44435978e-02,  2.23461781e-02, -1.58056840e-02, -3.96063514e-02,
         6.19643833e-03,  3.06795016e-02,  1.50323734e-02, -3.01858578e-02,
        -5.63730393e-03,  7.23949820e-03,  4.44135861e-03,  3.83775048e-02,
        -2.77931523e-02, -1.08045423e-02, -2.09066756e-02, -3.82518279e-03,
         1.28809130e-02, -7.62624592e-02,  2.56193690e-02,  5.03177643e-02,
        -1.48145370e-02, -9.30032656e-02,  1.84821772e-06, -2.72034351e-02,
         2.04363447e-02,  3.49979438e-02, -7.01642409e-02,  8.21791142e-02,
         9.58014093e-03,  1.12016927e-02,  1.45271542e-02,  2.08604950e-02,
         1.88052992e-03,  1.94313340e-02,  4.30906303e-02, -6.63991943e-02,
        -4.47118841e-03,  9.62141249e-03, -1.76184904e-02, -9.32420045e-02,
        -1.74521878e-02,  1.43797714e-02,  9.59808752e-02,  1.59285739e-02,
         3.41024175e-02,  9.89577454e-03,  2.74769589e-03, -3.97160538e-02,
         1.76487640e-02, -2.50339378e-02,  4.65405323e-02,  5.50866453e-03,
         3.66739929e-02,  8.11415240e-02,  1.02665706e-03, -3.91495274e-03,
         1.02581196e-02,  3.18636298e-02, -4.20973860e-02, -6.66075060e-03,
         2.48229466e-02,  1.19641721e-02, -2.52436493e-02,  1.71536375e-02,
         3.19568180e-02, -4.50095758e-02,  2.03785244e-02,  3.80981900e-02,
        -2.11242232e-02,  1.18821030e-02, -3.76307667e-04, -8.87247792e-04,
         7.49150217e-02, -1.01156048e-02, -2.94809025e-02,  7.10157258e-03,
         6.48592487e-02, -1.94446548e-05, -1.11182496e-01, -5.66404238e-02,
        -2.52492782e-02,  1.38240606e-02,  7.55137345e-03, -1.46898190e-02,
         2.22207401e-02,  5.33678103e-04,  2.86545623e-02, -6.54062778e-02,
         2.24799216e-02,  5.24192043e-02, -2.71777771e-02,  8.84031504e-03,
        -1.05444808e-02, -4.95063548e-04, -1.30082760e-02,  3.40696238e-02,
         2.00968443e-05, -1.76007692e-02,  8.07829294e-03, -6.34984253e-03,
        -4.88275327e-02,  4.00034972e-02,  1.75283588e-02,  9.74303950e-03,
         1.14658917e-03,  6.90653827e-03, -3.30178775e-02, -3.02616730e-02,
        -3.29962373e-02,  2.22184379e-02,  3.96934189e-02,  3.49612981e-02,
        -8.87161344e-02,  1.60383303e-02, -1.26949686e-03, -2.32299864e-02,
        -1.26420306e-02,  2.95909792e-02,  2.31829248e-02,  1.65003501e-02,
        -3.81323472e-02,  3.05584334e-02,  4.51847129e-02,  2.07054485e-02,
        -1.63255399e-03,  6.37390930e-03, -2.33271886e-02, -5.73715195e-02,
        -5.11532128e-02, -4.93464358e-02, -3.44207659e-02, -2.04843972e-02,
        -2.87391823e-02,  5.63038290e-02, -8.33715778e-03,  2.81261466e-03,
         2.13627089e-02, -1.49662178e-02, -5.19253723e-02,  2.39164308e-02,
         4.13530953e-02,  3.56319100e-02,  8.95309448e-03, -3.69550213e-02,
        -3.16563658e-02, -9.72753391e-03, -2.04478446e-02,  8.17026049e-02,
        -1.99236237e-02, -1.28493579e-02,  1.64389890e-03, -4.63711470e-02,
        -1.17448429e-02,  4.12844568e-02, -5.67117333e-03,  2.24809926e-02,
        -3.83236520e-02, -1.59223378e-02,  2.21639033e-02, -2.22279932e-02,
        -1.54940663e-02, -1.01862906e-03,  7.21554831e-02, -2.41181012e-02,
        -1.79879554e-02,  9.44159739e-03, -3.65188234e-02, -1.49370392e-03,
         6.17680661e-02,  5.66991717e-02,  4.52418439e-02,  2.77483352e-02,
        -3.50607671e-02,  9.84824542e-03,  3.15149389e-02,  5.07388674e-02,
        -1.77961588e-02, -3.29665653e-02,  1.27585670e-02,  2.99521666e-02,
         3.04353014e-02,  1.07564889e-02,  8.39108601e-03,  3.33771035e-02,
        -4.95182276e-02,  2.59656087e-02,  2.12876918e-03, -2.50242680e-04,
         6.51650578e-02,  5.81840947e-02,  3.07667982e-02, -2.88983714e-03,
        -1.51140848e-02, -3.88629409e-03, -2.01706383e-02,  4.65609618e-02,
        -1.68076698e-02, -6.59578145e-02, -1.26033779e-02, -1.55909751e-02,
        -6.79296791e-04, -3.24725099e-02, -6.40972517e-03,  3.73333250e-03,
        -1.18836379e-02,  3.81205454e-02, -2.22536791e-02,  5.33905812e-02,
         3.00371274e-02,  1.18945474e-02,  5.80814779e-02, -2.68650390e-02,
         7.29336813e-02,  2.93379761e-02,  5.82009107e-02, -5.18405288e-02,
        -2.97832955e-02,  3.41012552e-02,  3.58817354e-02,  2.01626979e-02,
         1.53031049e-03,  3.30130849e-03, -2.03335807e-02,  2.88390256e-02,
         1.79472845e-02,  3.13740745e-02,  5.43468492e-03,  5.02344184e-02,
        -2.97928229e-02, -5.50696403e-02, -6.76094042e-03, -7.79467868e-04,
        -1.20694311e-02,  2.82924790e-02,  2.94354698e-03, -2.83945203e-02,
        -2.30177864e-02, -9.66011640e-03, -4.08908539e-03, -3.00462078e-02,
        -5.52086905e-03,  3.04492051e-03, -1.92805938e-02, -1.19101536e-02,
         1.14658440e-03, -2.52537839e-02,  2.08762269e-02,  7.25417072e-03,
         6.35353327e-02, -2.79529742e-03,  1.50288017e-02,  3.25876959e-02,
        -6.62059113e-02, -6.57664761e-02, -4.48119491e-02,  5.92018515e-02,
         4.68914816e-03, -1.12712122e-02, -1.91877820e-02,  5.61325662e-02,
         4.85782623e-02,  2.94703022e-02,  3.55924144e-02,  5.80264162e-03,
         4.88805166e-03, -4.76187877e-02, -3.37588638e-02, -8.45588464e-03,
         1.14556774e-02,  2.67739072e-02,  1.23477252e-02,  2.00255271e-02,
         1.81062073e-02,  6.46771118e-03, -6.97587132e-02, -2.74993498e-02,
        -7.13092322e-03, -2.73373034e-02,  7.44503886e-02,  1.47062857e-02,
        -1.30421147e-02,  9.73012671e-03, -3.36028300e-02,  2.02024449e-02,
         3.13419662e-02, -7.58526381e-03, -1.71299221e-03, -2.14764997e-02,
         1.32148284e-02,  2.89806607e-03,  5.57681173e-03,  1.89360026e-02,
        -7.54976133e-03,  5.85188568e-02, -3.90172703e-03,  9.89190652e-04,
         1.98942702e-02,  8.60820990e-03,  2.15447620e-02,  2.29394473e-02,
         6.50780648e-03,  4.21973206e-02,  8.26636702e-03, -2.81754695e-02,
         7.21110730e-03, -2.69675367e-02,  7.82311857e-02, -2.18505990e-02,
        -1.21231731e-02,  1.76022369e-02, -1.50717171e-02, -1.42517090e-02,
        -8.10355321e-03,  3.10533820e-03, -1.54156281e-04, -1.05307959e-02,
        -8.38614330e-02,  2.03410257e-02, -2.97046863e-02,  2.18859278e-02,
         3.91102210e-02,  4.04879935e-02,  1.79388169e-02, -7.44179823e-03,
        -1.97079200e-02,  9.81899500e-02, -3.58329006e-02, -5.74958324e-02,
        -1.95771344e-02, -4.07495722e-02, -2.19417736e-02, -2.51251906e-02,
         5.03384173e-02, -9.53012798e-03,  7.42822662e-02, -3.41525039e-04,
        -3.74951051e-03,  2.93305162e-02,  1.55237643e-03, -2.88340729e-02,
        -1.85488723e-02, -1.90557316e-02, -4.09589969e-02, -3.18212286e-02,
         2.95139533e-02,  3.23088095e-03, -2.50308122e-02,  1.53751243e-02,
         4.33425419e-02,  5.10641467e-03, -2.58109439e-02, -7.54621997e-02,
        -1.04838973e-02,  4.82506603e-02, -1.21016791e-02, -5.31354882e-02,
         2.99499407e-02, -3.44397984e-02,  1.44982161e-02,  3.35098058e-02,
         4.15852182e-02, -1.07931914e-02,  1.73436869e-02,  1.92255061e-02,
         2.45624296e-02,  4.63915616e-02, -5.21132583e-03, -1.41820665e-02,
         4.22138125e-02, -6.33322224e-02,  4.98141982e-02, -2.07672697e-02,
        -7.48898089e-02, -2.81311516e-02, -7.68960034e-03, -3.19059752e-02,
        -1.94262043e-02, -3.94592546e-02,  3.08891572e-02,  5.22624981e-03,
        -2.11188830e-02,  2.72949152e-02,  3.95513214e-02, -2.35161204e-02,
         2.23498642e-02,  1.15609514e-02, -4.94572371e-02,  3.27671804e-02,
         6.16607964e-02, -4.80518006e-02,  1.66053176e-02, -3.90644670e-02,
         1.80994272e-02, -4.69239950e-02,  2.08608024e-02, -4.26505832e-03,
         2.95830797e-02,  2.67971456e-02,  2.06798757e-03,  1.40325613e-02,
         1.39026968e-02, -3.42218205e-02,  4.16489802e-02,  4.45410348e-02,
         2.13968791e-02,  2.67350022e-02,  2.34731324e-02,  4.50120158e-02,
        -6.25007898e-02, -8.93840380e-03, -1.02569843e-02,  3.47212926e-02,
        -2.72306707e-02, -5.27837127e-02, -6.72355369e-02, -2.41084639e-02,
        -6.29305914e-02, -2.45558266e-02,  6.79910332e-02, -1.71199236e-02,
        -5.19692060e-03, -2.50085238e-02,  4.36813192e-04, -5.29311132e-04,
         5.64266481e-02, -3.68509963e-02,  1.27865106e-03,  4.36809063e-02,
         3.42691480e-03,  7.88338389e-03, -4.34135161e-02, -4.49230485e-02,
         8.90783444e-02,  1.74692292e-02,  2.03296281e-02, -1.01353750e-02,
        -9.39849298e-03,  8.80940557e-02, -5.66902803e-03, -1.05300704e-02,
        -6.30244389e-02,  6.76475000e-03,  1.29810395e-03, -3.32524665e-02,
        -6.34878054e-02,  7.06905797e-02, -5.23132831e-03, -2.53332276e-02,
        -2.87126545e-02, -1.01521686e-02,  4.22699898e-02, -1.54305277e-02,
        -7.59011582e-02,  3.65060158e-02,  4.00408134e-02,  2.08072793e-02,
        -9.66928247e-03,  7.80477887e-03, -2.30107941e-02,  6.49472550e-02,
        -2.14785524e-02,  1.98700535e-03, -1.97604601e-03, -4.29251716e-02,
        -6.99224249e-02,  5.22380695e-02, -7.91266561e-02,  2.38740947e-02,
        -4.35845777e-02,  1.17662186e-02,  1.32625829e-02,  6.97017163e-02,
         4.33111675e-02, -4.57389466e-03,  6.64431751e-02, -3.31922993e-02,
         1.59750264e-02, -5.51458597e-02, -1.20564476e-02,  5.07313572e-03,
        -2.47540772e-02, -6.06123358e-02, -5.29980753e-03, -4.35960032e-02,
         4.77819704e-02,  3.37773263e-02, -2.80110165e-02,  6.84495419e-02,
         6.60215989e-02,  2.77555943e-03,  3.83193344e-02, -4.94900309e-02,
         1.73597448e-02, -2.41690278e-02, -2.11087428e-02,  4.73575387e-03,
         3.32153067e-02,  5.93856312e-02,  9.94156301e-03,  2.92046163e-02,
        -2.83259824e-02,  3.52802724e-02, -4.07908894e-02, -5.74266650e-02,
         2.63905171e-02, -7.08783567e-02,  1.73162278e-02,  5.38091408e-03,
         1.15250945e-02, -2.14818642e-02,  2.60813092e-03,  3.82594578e-02,
        -6.18264787e-02,  9.82393976e-03,  3.29365954e-02,  9.30187758e-03,
        -6.35777861e-02,  8.44492912e-02,  1.37453433e-03,  1.92110951e-03,
        -2.84220316e-02,  4.92005870e-02,  1.61023904e-02,  1.69644207e-02,
         1.62301455e-02,  2.92290235e-03,  3.85008976e-02, -4.31264527e-02,
         1.44625632e-02, -1.80732589e-02,  5.74169271e-02, -3.90737094e-02,
         8.29734281e-02, -1.12668220e-02, -5.81889264e-02, -3.74181345e-02,
         1.12795522e-02, -1.26190037e-01,  5.36711421e-03, -4.74466709e-03,
        -3.80182862e-02, -3.80317867e-02,  3.38512883e-02, -5.65267462e-33,
         3.12506147e-02, -2.74420623e-02,  1.49309654e-02,  9.66008604e-02,
         3.82223018e-02,  6.07445277e-02, -8.67401809e-03, -2.20907759e-02,
        -3.87738273e-02,  3.14043984e-02, -2.78094113e-02, -2.61556227e-02,
        -2.18033092e-03, -5.67599460e-02, -3.29962559e-02, -3.37906405e-02,
         2.51040608e-02,  1.20999021e-02, -4.59938357e-03, -2.30384944e-03,
        -8.03607628e-02, -2.47460958e-02,  3.90837267e-02, -3.80970165e-02,
         7.66094476e-02,  3.75051275e-02,  1.00947674e-02, -7.00766221e-02,
        -2.27734894e-02,  3.35722789e-02, -2.90578492e-02, -3.86456936e-03,
         3.98564376e-02, -3.37578319e-02, -2.65688077e-02,  8.76989365e-02,
         8.22846871e-03, -1.56535432e-02, -1.40035572e-02,  2.47986875e-02,
        -3.26930843e-02, -2.71499995e-02, -2.48089116e-02, -1.73133817e-02,
        -4.77490723e-02,  4.30413075e-02,  1.23732937e-02,  1.67823303e-02,
         5.97122610e-02,  1.10688517e-02, -2.47990489e-02, -4.01355233e-03,
         3.85954864e-02,  7.99259543e-03,  4.08465602e-02,  8.16079006e-02,
         1.41680967e-02, -1.61755811e-02,  4.62705716e-02,  6.75018281e-02,
         4.88048606e-03,  4.43557501e-02, -5.26424833e-02,  4.46237661e-02,
         1.51577713e-02, -3.11318375e-02, -2.43334868e-03, -1.35898069e-02,
        -5.16745038e-02, -1.28283482e-02, -4.79294062e-02,  1.57728264e-05,
         5.55568375e-02,  7.30251987e-03,  1.25851378e-01, -7.46831298e-02,
        -3.31933573e-02, -2.04486903e-02, -8.40956494e-02, -9.70691144e-02,
        -2.75885599e-04, -2.53043920e-02,  3.13058197e-02, -2.38177404e-02,
        -2.50919275e-02,  1.06879972e-01, -8.03863909e-03, -4.56797034e-02,
        -1.87865160e-02, -6.08093999e-02,  4.03947979e-02,  6.67790696e-03,
        -3.44066136e-02,  5.60434870e-02,  2.06243452e-02,  7.52738584e-03,
         3.48817222e-02, -8.49589333e-03,  2.34857271e-03, -5.82642294e-03,
        -4.84207794e-02,  2.79288646e-02,  2.19938159e-02,  1.34437308e-02,
        -3.05742677e-02, -2.82639414e-02, -5.49180172e-02,  4.83709723e-02,
         2.10338552e-02, -4.58570495e-02, -8.81958473e-03,  3.36519107e-02,
         3.62561569e-02, -5.10728769e-02, -5.84396049e-02,  7.98112829e-04,
         1.99138280e-02,  2.59554442e-02, -9.53386538e-03, -2.35024523e-02,
        -6.40766621e-02, -9.99837741e-03,  6.02089576e-02, -1.54787861e-02,
         1.46333314e-02, -2.73179226e-02,  2.11187582e-02, -7.98223615e-02,
        -6.87027127e-02,  9.48770531e-03, -1.09383278e-02,  1.36643304e-02,
         2.81300316e-07,  1.70468427e-02,  1.37893185e-02, -1.67372245e-02,
         3.99160199e-02, -5.93482181e-02, -8.79671425e-03,  4.47691679e-02,
        -2.94926669e-02, -3.48558314e-02, -3.94704938e-02,  1.52495445e-03,
        -5.70393130e-02, -1.58385076e-02,  2.68248599e-02, -2.32512448e-02,
         1.21564139e-02, -1.29619874e-02, -6.76471069e-02,  3.04765683e-02,
         2.22088899e-02, -7.54231587e-03, -1.48998657e-02, -1.43285943e-02,
        -3.65560055e-02, -3.22323404e-02,  1.44279031e-02, -5.36745321e-03,
        -1.84829067e-02,  6.61565587e-02,  2.09395438e-02,  3.05020600e-03,
         1.59577392e-02,  3.94967310e-02, -2.02135704e-02, -2.40854379e-02,
        -2.85920016e-02, -2.59215645e-02, -8.99069458e-02, -1.97141357e-02,
        -8.99936855e-02, -3.41935229e-05,  1.10064296e-03, -2.26069875e-02,
         1.26896380e-03, -3.18909436e-02, -3.87221053e-02, -7.64146075e-03,
         1.19272862e-02,  6.19138628e-02, -5.65737560e-02, -9.06444155e-03,
         4.63988334e-02, -2.26716883e-02,  5.40704525e-04,  3.30266985e-03,
         7.85039505e-04, -5.53773809e-03,  2.09835358e-02,  1.68783255e-02,
         7.32702296e-03,  1.08058983e-02,  3.89462188e-02, -3.56237292e-02,
         1.80466548e-02, -1.45939318e-02,  4.73403698e-03,  1.92299895e-02,
         2.68856428e-34,  1.68735441e-03, -5.82957789e-02,  2.25708298e-02,
         6.02850225e-03, -3.00494041e-02,  3.22193876e-02, -1.27366437e-02,
         3.73876765e-02,  2.93491501e-03,  4.22898680e-02, -1.54304353e-03],
       dtype=float32)}

In [59]:
text_chunk_embedding_df = pd.DataFrame(pages_and_chunks_over_min_token_length)

embedding_df_save_path = "D:\\Projects\\Local_Mini_RAG\\text_chunk_embeddings.csv"

text_chunk_embedding_df.to_csv(embedding_df_save_path, index=False)

In [60]:
text_chunk_embedding_df_load = pd.read_csv(embedding_df_save_path)

text_chunk_embedding_df_load.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-39,Human Nutrition: 2020 Edition UNIVERSITY OF HA...,308,42,77.0,[ 6.74242526e-02 9.02281031e-02 -5.09549724e-...
1,-38,Human Nutrition: 2020 Edition by University of...,210,30,52.5,[ 5.52156046e-02 5.92139363e-02 -1.66167300e-...
2,-37,Contents Preface University of Hawai‘i at Māno...,766,114,191.5,[ 2.79801898e-02 3.39813866e-02 -2.06426680e-...
3,-36,Lifestyles and Nutrition University of Hawai‘i...,942,143,235.5,[ 6.82566911e-02 3.81274968e-02 -8.46854970e-...
4,-35,The Cardiovascular System University of Hawai‘...,998,152,249.5,[ 3.30264494e-02 -8.49766005e-03 9.57159698e-...